// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vxkembmfsoyclyuykdyg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ4a2VtYm1mc295Y2x5dXlrZHlnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2MzUxNDYsImV4cCI6MjA3MTIxMTE0Nn0.TeuKod07jROaskRkuzsYzwrjTSaO6DH3nVQFnFbjGpM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});